# Generated by Django 2.0.5 on 2018-12-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='table_number',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
