# Generated by Django 2.0.5 on 2018-12-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarentapp', '0002_orderitem_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='photo',
            field=models.ImageField(blank=True, upload_to='property_image'),
        ),
    ]
