# Generated by Django 2.0.5 on 2018-12-31 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarentapp', '0005_auto_20181231_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
