# Generated by Django 2.0.5 on 2019-01-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restuarentapp', '0006_remove_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.IntegerField(default='120'),
            preserve_default=False,
        ),
    ]
